FROM python:3.6.5

ARG SLACK_WEBHOOK_URL_ARG=UNSPECIFIED
ARG CLUSTER_NAMESPACE_ARG=UNSPECIFIED

ENV SLACK_WEBHOOK_URL=SLACK_WEBHOOK_URL
ENV CLUSTER_NAMESPACE=$CLUSTER_NAMESPACE_ARG

WORKDIR /app

COPY src .

RUN pip install -r requirements.txt

ENTRYPOINT ["python", "main.py"]
